services:
  qgis:
    image: qgis/qgis:3.34.14
    container_name: qgis_sigpac
    command: qgis
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../sigpac_downloader:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/
      - ./QGIS3.ini:/root/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini